//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NETApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int ItemsID { get; set; }
        public Nullable<double> Price { get; set; }
        public string Name { get; set; }
        public Nullable<int> OrderDetailId { get; set; }
    
        public virtual OrderDetail OrderDetail { get; set; }
    }
}
